version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      compose:
        patterns:
          - "org.jetbrains.compose*"
      android:
        patterns:
          - "com.android*"
      maven-publish:
        patterns:
          - "com.vanniktech*"
      kommon:
        patterns:
          - "io.github.maniramezan.kommon*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
